# Generated by Django 5.2.9 on 2026-02-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kyc_id',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_ids/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
