# Generated by Django 5.2.9 on 2026-02-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_profile_bio_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='action_taken',
            field=models.CharField(choices=[('none', 'None Taken'), ('warning', 'Warning Issued'), ('suspension', 'User Suspended'), ('fine', 'Fine Issued')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
