# Generated by Django 5.2.9 on 2026-04-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_payment_pidx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="pidx",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
