# Generated by Django 5.2.9 on 2026-04-08 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_alter_payment_pidx"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
